2. 使用環境

Jupyter Notebook

Python 3.x

pandas

re

3. データ読み込み

In [1]:

import pandas as pd
import re


# CSV ファイルのパス
csv_path = r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC_ToBrick_IoT_Interoperability_Project\data\resources\BDNS_Abbreviations_Register_v2.0.0.csv"

# CSV の読み込み
df = pd.read_csv(csv_path)

# データ構造の確認
df.head()

,asset_description,asset_abbreviation,can_be_connected,dbo_entity_type,ifc4_3,ifc2x3
0,access control - RFID controller,RFIDC,1,NaN,IfcController,IfcController
1,access control - RFID reader,RFIDR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER
2,access control - access control system,ACS,1,NaN,IfcDistributionSystemSECURITY,NaN
3,access control - audio intercom,AIC,1,NaN,IfcSwitchingDevice,IfcSwitchingDevice
4,access control - biometric reader,BIOR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER

4. ifc4_3 列のカバー範囲抽出
方針

欠損値は分析対象外とする

データ型を文字列に統一し疑似重複を防止する

unique により列内重複を排除する

In [2]:


ifc4_3_unique = (
    df["ifc4_3"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

ifc4_3_unique_sorted = sorted(ifc4_3_unique)

ifc4_3_unique_sorted

['IfcActuator',
 'IfcActuatorELECTRICACTUATOR',
 'IfcAirTerminal',
 'IfcAirTerminalBox',
 'IfcAirTerminalBoxCONSTANTFLOW',
 'IfcAirToAirHeatRecovery',
 'IfcAirToAirHeatRecoveryROTARYWHEEL',
 'IfcAirToAirHeatRecoveryRUNAROUNDCOIL',
 'IfcAlarm',
 'IfcAlarmBELL',
 'IfcAlarmBREAKGLASSBUTTON',
 'IfcAlarmLIGHT',
 'IfcAlarmMANUALPULLBOX',
 'IfcAlarmSIREN',
 'IfcAudioVisualAppliance',
 'IfcAudioVisualApplianceAMPLIFIER',
 'IfcAudioVisualApplianceCAMERA',
 'IfcAudioVisualApplianceCOMMUNICATIONTERMINAL',
 'IfcAudioVisualApplianceDISPLAY',
 'IfcAudioVisualApplianceMICROPHONE',
 'IfcAudioVisualAppliancePLAYER',
 'IfcAudioVisualApplianceRECEIVER',
 'IfcAudioVisualApplianceSPEAKER',
 'IfcAudioVisualApplianceSWITCHER',
 'IfcAudioVisualApplianceTUNER',
 'IfcBoiler',
 'IfcBoilerSTEAM',
 'IfcBoilerWATER',
 'IfcBurner',
 'IfcCableCarrierSegment',
 'IfcCableCarrierSegmentCABLELADDERSEGMENT',
 'IfcCableCarrierSegmentCABLETRAYSEGMENT',
 'IfcCableCarrierSegmentCABLETRUNKINGSEGMENT',
 'IfcCableSegment',
 'IfcCableSegmentBUSBARSEGMENT',
 'IfcCableSegmentFIBERTUBE',
 'IfcChiller',
 'IfcChillerAIRCOOLED',
 'IfcChillerWATERCOOLED',
 'IfcCoilDXCOOLINGCOIL',
 'IfcCoilHYDRONICCOIL',
 'IfcCoilHYDRONICCOIL,IfcCoil',
 'IfcCoilWATERCOOLINGCOIL',
 'IfcCoilWATERHEATINGCOIL',
 'IfcCommunicationsAppliance',
 'IfcCommunicationsApplianceANTENNA',
 'IfcCommunicationsApplianceGATEWAY',
 'IfcCommunicationsApplianceNETWORKAPPLIANCE',
 'IfcCommunicationsApplianceNETWORKBRIDGE',
 'IfcCommunicationsAppliancePRINTER',
 'IfcCommunicationsApplianceROUTER',
 'IfcCommunicationsApplianceSCANNER',
 'IfcCompressor',
 'IfcCondenser',
 'IfcCondenserAIRCOOLED',
 'IfcController',
 'IfcControllerPROGRAMMABLE',
 'IfcControllerTWOPOSITION',
 'IfcCooledBeam',
 'IfcCooledBeamACTIVE',
 'IfcCooledBeamPASSIVE',
 'IfcCoolingTower',
 'IfcDamper',
 'IfcDamperBALANCINGDAMPER',
 'IfcDamperCONTROLDAMPER',
 'IfcDamperFIREDAMPER',
 'IfcDamperFIRESMOKEDAMPER',
 'IfcDamperFUMEHOODEXHAUST',
 'IfcDamperRELIEFDAMPER',
 'IfcDamperSMOKEDAMPER',
 'IfcDistributionBoard',
 'IfcDistributionBoardCONSUMERUNIT',
 'IfcDistributionBoardDISTRIBUTIONBOARD',
 'IfcDistributionBoardSWITCHBOARD',
 'IfcDistributionElement',
 'IfcDistributionSystem',
 'IfcDistributionSystemFIREPROTECTION',
 'IfcDistributionSystemSECURITY',
 'IfcDoorDOOR',
 'IfcDuctSegment',
 'IfcDuctSilencer',
 'IfcElectricAppliance',
 'IfcElectricApplianceDISHWASHER',
 'IfcElectricApplianceELECTRICCOOKER',
 'IfcElectricApplianceFREESTANDINGWATERHEATER',
 'IfcElectricApplianceFREEZER',
 'IfcElectricApplianceMICROWAVE',
 'IfcElectricApplianceREFRIGERATOR',
 'IfcElectricApplianceTUMBLEDRYER',
 'IfcElectricApplianceVENDINGMACHINE',
 'IfcElectricApplianceWASHINGMACHINE',
 'IfcElectricFlowStorageDevice',
 'IfcElectricFlowStorageDeviceBATTERY',
 'IfcElectricFlowStorageDeviceHARMONICFILTER',
 'IfcElectricFlowStorageDeviceUPS',
 'IfcElectricFlowTreatmentDevice',
 'IfcElectricGenerator',
 'IfcElectricGeneratorCHP',
 'IfcElectricGeneratorENGINEGENERATOR',
 'IfcElectricMotor',
 'IfcElectricTimeControlTIMECLOCK',
 'IfcEvaporativeCooler',
 'IfcEvaporator',
 'IfcFan',
 'IfcFastener',
 'IfcFilter',
 'IfcFilterAIRPARTICLEFILTER',
 'IfcFilterWATERFILTER',
 'IfcFireSuppressionTerminal',
 'IfcFireSuppressionTerminalHOSEREEL',
 'IfcFireSuppressionTerminalSPRINKLER',
 'IfcFlowMeter',
 'IfcFlowMeterENERGYMETER',
 'IfcFlowMeterGASMETER',
 'IfcFlowMeterWATERMETER',
 'IfcFlowTerminal',
 'IfcFlowTreatmentDevice',
 'IfcFurniture',
 'IfcFurnitureDESK',
 'IfcFurnitureSHELF',
 'IfcGroup',
 'IfcHeatExchanger',
 'IfcHeatExchangerPLATE',
 'IfcHumidifier',
 'IfcInterceptor',
 'IfcInterceptorGREASE',
 'IfcInterceptorOIL',
 'IfcLightFixture',
 'IfcLightFixtureDIRECTIONSOURCE',
 'IfcLightFixturePOINTSOURCE',
 'IfcLightFixtureSECURITYLIGHTING',
 'IfcMotorConnection',
 'IfcOutlet',
 'IfcOutletDATAOUTLET',
 'IfcOutletPOWEROUTLET',
 'IfcPipeSegment',
 'IfcProtectiveDevice',
 'IfcProtectiveDeviceCIRCUITBREAKER',
 'IfcProtectiveDeviceFUSEDISCONNECTOR',
 'IfcProtectiveDeviceRESIDUALCURRENTCIRCUITBREAKER',
 'IfcProtectiveDeviceVARISTOR',
 'IfcPump',
 'IfcPumpCIRCULATOR',
 'IfcPumpSUMPPUMP',
 'IfcSanitaryTerminalSANITARYFOUNTAIN',
 'IfcSanitaryTerminalSINK',
 'IfcSanitaryTerminalWASHHANDBASIN',
 'IfcSensor',
 'IfcSensorCO2SENSOR',
 'IfcSensorCONTACTSENSOR',
 'IfcSensorCOSENSOR',
 'IfcSensorFLOWSENSOR',
 'IfcSensorGASSENSOR',
 'IfcSensorHEATSENSOR',
 'IfcSensorHUMIDITYSENSOR',
 'IfcSensorLIGHTSENSOR',
 'IfcSensorMOVEMENTSENSOR',
 'IfcSensorPRESSURESENSOR',
 'IfcSensorRADIATIONSENSOR',
 'IfcSensorSMOKESENSOR',
 'IfcSensorSOUNDSENSOR',
 'IfcSensorTEMPERATURESENSOR',
 'IfcSensorWINDSENSOR',
 'IfcShadingDevice',
 'IfcSolarDeviceSOLARCOLLECTOR',
 'IfcSolarDeviceSOLARPANEL',
 'IfcSpaceHeater',
 'IfcSpaceHeaterRADIATOR',
 'IfcSpaceINTERNAL',
 'IfcStackTerminal',
 'IfcSwitchingDevice',
 'IfcSwitchingDeviceCONTACTOR',
 'IfcSwitchingDeviceDIMMERSWITCH',
 'IfcSwitchingDeviceKEYPAD',
 'IfcSwitchingDeviceSELECTORSWITCH',
 'IfcSwitchingDeviceSWITCHDISCONNECTOR',
 'IfcSwitchingDeviceTOGGLESWITCH',
 'IfcTank',
 'IfcTankBREAKPRESSURE',
 'IfcTankEXPANSION',
 'IfcTankSTORAGE',
 'IfcTankVESSEL',
 'IfcTransformer',
 'IfcTransformerINVERTER',
 'IfcTransformerRECTIFIER',
 'IfcTransportElementELEVATOR',
 'IfcTransportElementESCALATOR',
 'IfcTransportElementMOVINGWALKWAY',
 'IfcUnitaryControlElement',
 'IfcUnitaryControlElementALARMPANEL',
 'IfcUnitaryControlElementCONTROLPANEL',
 'IfcUnitaryControlElementGASDETECTIONPANEL',
 'IfcUnitaryControlElementINDICATORPANEL',
 'IfcUnitaryControlElementTHERMOSTAT',
 'IfcUnitaryControlElementWEATHERSTATION',
 'IfcUnitaryEquipment',
 'IfcUnitaryEquipmentAIRCONDITIONINGUNIT',
 'IfcUnitaryEquipmentAIRHANDLER',
 'IfcUnitaryEquipmentDEHUMIDIFIER',
 'IfcUnitaryEquipmentROOFTOPUNIT',
 'IfcUnitaryEquipmentSPLITSYSTEM',
 'IfcValve',
 'IfcValveAIRRELEASE',
 'IfcValveCHECK',
 'IfcValveCOMMISSIONING',
 'IfcValveDIVERTING',
 'IfcValveGASCOCK',
 'IfcValveISOLATING',
 'IfcValveMIXING',
 'IfcValvePRESSUREREDUCING',
 'IfcValvePRESSURERELIEF',
 'IfcValveSAFETYCUTOFF',
 'IfcValveSTEAMTRAP',
 'IfcWasteTerminal',
 'IfcWindow']

5. ifc2x3 列のカバー範囲抽出

In [3]:
ifc2x3_unique = (
    df["ifc2x3"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

ifc2x3_unique_sorted = sorted(ifc2x3_unique)

ifc2x3_unique_sorted

['IfcActuator',
 'IfcActuatorELECTRICACTUATOR',
 'IfcAirTerminal',
 'IfcAirTerminalBox',
 'IfcAirTerminalBoxCONSTANTFLOW',
 'IfcAirToAirHeatRecovery',
 'IfcAirToAirHeatRecoveryROTARYWHEEL',
 'IfcAirToAirHeatRecoveryRUNAROUNDCOIL',
 'IfcAlarm',
 'IfcAlarmBELL',
 'IfcAlarmBREAKGLASSBUTTON',
 'IfcAlarmLIGHT',
 'IfcAlarmMANUALPULLBOX',
 'IfcAlarmSIREN',
 'IfcBoiler',
 'IfcBoilerSTEAM',
 'IfcBoilerWATER',
 'IfcBuildingElementProxy',
 'IfcCableCarrierSegment',
 'IfcCableCarrierSegmentCABLELADDERSEGMENT',
 'IfcCableCarrierSegmentCABLETRAYSEGMENT',
 'IfcCableCarrierSegmentCABLETRUNKINGSEGMENT',
 'IfcCableSegment',
 'IfcCableSegmentFIBERTUBE',
 'IfcChiller',
 'IfcChillerAIRCOOLED',
 'IfcChillerWATERCOOLED',
 'IfcCoil',
 'IfcCoilDXCOOLINGCOIL',
 'IfcCoilHYDRONICCOIL',
 'IfcCoilWATERCOOLINGCOIL',
 'IfcCoilWATERHEATINGCOIL',
 'IfcCompressor',
 'IfcCondenser',
 'IfcCondenserAIRCOOLED',
 'IfcController',
 'IfcControllerTWOPOSITION',
 'IfcCooledBeam',
 'IfcCoolingTower',
 'IfcDamper',
 'IfcDamperBALANCINGDAMPER',
 'IfcDamperCONTROLDAMPER',
 'IfcDamperFIREDAMPER',
 'IfcDamperFIRESMOKEDAMPER',
 'IfcDamperFUMEHOODEXHAUST',
 'IfcDamperRELIEFDAMPER',
 'IfcDamperSMOKEDAMPER',
 'IfcDiscreteAccessory',
 'IfcDoorStyle',
 'IfcDuctSegment',
 'IfcDuctSilencer',
 'IfcElectricAppliance',
 'IfcElectricApplianceDISHWASHER',
 'IfcElectricApplianceELECTRICCOOKER',
 'IfcElectricApplianceFREEZER',
 'IfcElectricApplianceMICROWAVE',
 'IfcElectricAppliancePRINTER',
 'IfcElectricApplianceREFRIGERATOR',
 'IfcElectricApplianceSCANNER',
 'IfcElectricApplianceTUMBLEDRYER',
 'IfcElectricApplianceVENDINGMACHINE',
 'IfcElectricApplianceWASHINGMACHINE',
 'IfcElectricApplianceWATERHEATER',
 'IfcElectricDistributionPoint',
 'IfcElectricDistributionPointALARMPANEL',
 'IfcElectricDistributionPointCONTROLPANEL',
 'IfcElectricDistributionPointDISTRIBUTIONBOARD',
 'IfcElectricDistributionPointGASDETECTORPANEL',
 'IfcElectricDistributionPointSWITCHBOARD',
 'IfcElectricFlowStorageDevice',
 'IfcElectricFlowStorageDeviceBATTERY',
 'IfcElectricFlowStorageDeviceHARMONICFILTER',
 'IfcElectricFlowStorageDeviceUPS',
 'IfcElectricGenerator',
 'IfcElectricMotor',
 'IfcElectricTimeControlTIMECLOCK',
 'IfcEvaporativeCooler',
 'IfcEvaporator',
 'IfcFan',
 'IfcFastener',
 'IfcFilter',
 'IfcFilterAIRPARTICLEFILTER',
 'IfcFilterWATERFILTER',
 'IfcFireSuppressionTerminal',
 'IfcFireSuppressionTerminalHOSEREEL',
 'IfcFireSuppressionTerminalSPRINKLER',
 'IfcFlowMeter',
 'IfcFlowMeterENERGYMETER',
 'IfcFlowMeterGASMETER',
 'IfcFlowMeterWATERMETER',
 'IfcFurniture',
 'IfcGasTerminalGASAPPLIANCE',
 'IfcHeatExchanger',
 'IfcHeatExchangerPLATE',
 'IfcHumidifier',
 'IfcLightFixture',
 'IfcLightFixtureDIRECTIONSOURCE',
 'IfcLightFixturePOINTSOURCE',
 'IfcMotorConnection',
 'IfcOutlet',
 'IfcOutletCOMMUNICATIONSOUTLET',
 'IfcOutletPOWEROUTLET',
 'IfcPipeSegment',
 'IfcProtectiveDevice',
 'IfcProtectiveDeviceCIRCUITBREAKER',
 'IfcProtectiveDeviceFUSEDISCONNECTOR',
 'IfcProtectiveDeviceRESIDUALCURRENTCIRCUITBREAKER',
 'IfcProtectiveDeviceVARISTOR',
 'IfcPump',
 'IfcPumpCIRCULATOR',
 'IfcSanitaryTerminalSANITARYFOUNTAIN',
 'IfcSanitaryTerminalSINK',
 'IfcSanitaryTerminalWASHHANDBASIN',
 'IfcSensor',
 'IfcSensorCO2SENSOR',
 'IfcSensorFLOWSENSOR',
 'IfcSensorGASSENSOR',
 'IfcSensorHEATSENSOR',
 'IfcSensorHUMIDITYSENSOR',
 'IfcSensorLIGHTSENSOR',
 'IfcSensorMOVEMENTSENSOR',
 'IfcSensorPRESSURESENSOR',
 'IfcSensorSMOKESENSOR',
 'IfcSensorSOUNDSENSOR',
 'IfcSensorTEMPERATURESENSOR',
 'IfcSpace',
 'IfcSpaceHeater',
 'IfcStackTerminal',
 'IfcSwitchingDevice',
 'IfcSwitchingDeviceCONTACTOR',
 'IfcSwitchingDeviceSWITCHDISCONNECTOR',
 'IfcSwitchingDeviceTOGGLESWITCH',
 'IfcTank',
 'IfcTankEXPANSION',
 'IfcTransformer',
 'IfcTransformerINVERTER',
 'IfcTransportElementELEVATOR',
 'IfcTransportElementESCALATOR',
 'IfcTransportElementMOVINGWALKWAY',
 'IfcUnitaryEquipment',
 'IfcUnitaryEquipmentAIRCONDITIONINGUNIT',
 'IfcUnitaryEquipmentAIRHANDLER',
 'IfcUnitaryEquipmentROOFTOPUNIT',
 'IfcUnitaryEquipmentSPLITSYSTEM',
 'IfcValve',
 'IfcValveAIRRELEASE',
 'IfcValveCHECK',
 'IfcValveCOMMISSIONING',
 'IfcValveDIVERTING',
 'IfcValveGASCOCK',
 'IfcValveISOLATING',
 'IfcValveMIXING',
 'IfcValvePRESSUREREDUCING',
 'IfcValvePRESSURERELIEF',
 'IfcValveSAFETYCUTOFF',
 'IfcValveSTEAMTRAP',
 'IfcWasteTerminal',
 'IfcWasteTerminalGREASEINTERCEPTOR',
 'IfcWasteTerminalOILINTERCEPTOR',
 'IfcWindowStyle']

6. 件数によるIFCカバー範囲の定量確認

In [4]:
print("Number of unique values in ifc4_3:", len(ifc4_3_unique_sorted))
print("Number of unique values in ifc2x3:", len(ifc2x3_unique_sorted))

Number of unique values in ifc4_3: 215
Number of unique values in ifc2x3: 160

7. 件数によるBDNSカバー範囲の定量確認

In [5]:
asset_abbreviation_unique = (
    df["asset_abbreviation"]
    .dropna()
    .astype(str)
    .unique()
)

asset_abbreviation_unique_count = len(asset_abbreviation_unique)
asset_abbreviation_unique_count
print("Number of unique values in asset_abbreviation:", asset_abbreviation_unique_count)

Number of unique values in asset_abbreviation: 748

8. Entity と PredefinedType を分解する関数定義

In [6]:
def split_ifc_entity_and_type(value):
    if pd.isna(value):
        return pd.Series([None, None])

    value = str(value)

    match = re.match(r"^(Ifc[A-Za-z0-9]+?)([A-Z]+)$", value)

    if match:
        entity = match.group(1)
        predefined_type = match.group(2)
        return pd.Series([entity, predefined_type])
    else:
        return pd.Series([value, None])

本関数は,
正規表現により

Ifc で始まる Entity 部分
末尾の大文字列からなる PredefinedType 部分

を分離する.
PredefinedType を持たないエンティティについては, Entity のみを保持する.

9.列の分解

In [7]:
df[["ifc2x3_entity", "ifc2x3_predefined_type"]] = (
    df["ifc2x3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc2x3", "ifc2x3_entity", "ifc2x3_predefined_type"]].head()

df[["ifc4_3_entity", "ifc4_3_predefined_type"]] = (
    df["ifc4_3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc4_3", "ifc4_3_entity", "ifc4_3_predefined_type"]].head()

,ifc4_3,ifc4_3_entity,ifc4_3_predefined_type
0,IfcController,IfcController,None
1,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER
2,IfcDistributionSystemSECURITY,IfcDistributionSystem,SECURITY
3,IfcSwitchingDevice,IfcSwitchingDevice,None
4,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER

In [9]:
#df.to_csv(r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC_ToBrick_IoT_Interoperability_Project\data\resources\BDNS_Abbreviations_Register_v2.0.0_curated.csv", index=False)