データ読み込み

In [1]:
import pandas as pd
import re
import ifcopenshell

# CSV ファイルのパス
csv_path = r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC_ToBrick_IoT_Interoperability_Project\data\resources\BDNS_Abbreviations_Register_v2.0.0.csv"

# CSV の読み込み
df = pd.read_csv(csv_path)

# データ構造の確認
df.head()

,asset_description,asset_abbreviation,can_be_connected,dbo_entity_type,ifc4_3,ifc2x3
0,access control - RFID controller,RFIDC,1,NaN,IfcController,IfcController
1,access control - RFID reader,RFIDR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER
2,access control - access control system,ACS,1,NaN,IfcDistributionSystemSECURITY,NaN
3,access control - audio intercom,AIC,1,NaN,IfcSwitchingDevice,IfcSwitchingDevice
4,access control - biometric reader,BIOR,1,NaN,IfcCommunicationsApplianceSCANNER,IfcElectricApplianceSCANNER

ifcのカバー範囲抽出

In [2]:
ifc4_3_unique = (
    df["ifc4_3"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

ifc4_3_unique_sorted = sorted(ifc4_3_unique)

ifc4_3_unique_sorted

['IfcActuator',
 'IfcActuatorELECTRICACTUATOR',
 'IfcAirTerminal',
 'IfcAirTerminalBox',
 'IfcAirTerminalBoxCONSTANTFLOW',
 'IfcAirToAirHeatRecovery',
 'IfcAirToAirHeatRecoveryROTARYWHEEL',
 'IfcAirToAirHeatRecoveryRUNAROUNDCOIL',
 'IfcAlarm',
 'IfcAlarmBELL',
 'IfcAlarmBREAKGLASSBUTTON',
 'IfcAlarmLIGHT',
 'IfcAlarmMANUALPULLBOX',
 'IfcAlarmSIREN',
 'IfcAudioVisualAppliance',
 'IfcAudioVisualApplianceAMPLIFIER',
 'IfcAudioVisualApplianceCAMERA',
 'IfcAudioVisualApplianceCOMMUNICATIONTERMINAL',
 'IfcAudioVisualApplianceDISPLAY',
 'IfcAudioVisualApplianceMICROPHONE',
 'IfcAudioVisualAppliancePLAYER',
 'IfcAudioVisualApplianceRECEIVER',
 'IfcAudioVisualApplianceSPEAKER',
 'IfcAudioVisualApplianceSWITCHER',
 'IfcAudioVisualApplianceTUNER',
 'IfcBoiler',
 'IfcBoilerSTEAM',
 'IfcBoilerWATER',
 'IfcBurner',
 'IfcCableCarrierSegment',
 'IfcCableCarrierSegmentCABLELADDERSEGMENT',
 'IfcCableCarrierSegmentCABLETRAYSEGMENT',
 'IfcCableCarrierSegmentCABLETRUNKINGSEGMENT',
 'IfcCableSegment',
 'IfcCableSegmentBUSBARSEGMENT',
 'IfcCableSegmentFIBERTUBE',
 'IfcChiller',
 'IfcChillerAIRCOOLED',
 'IfcChillerWATERCOOLED',
 'IfcCoilDXCOOLINGCOIL',
 'IfcCoilHYDRONICCOIL',
 'IfcCoilHYDRONICCOIL,IfcCoil',
 'IfcCoilWATERCOOLINGCOIL',
 'IfcCoilWATERHEATINGCOIL',
 'IfcCommunicationsAppliance',
 'IfcCommunicationsApplianceANTENNA',
 'IfcCommunicationsApplianceGATEWAY',
 'IfcCommunicationsApplianceNETWORKAPPLIANCE',
 'IfcCommunicationsApplianceNETWORKBRIDGE',
 'IfcCommunicationsAppliancePRINTER',
 'IfcCommunicationsApplianceROUTER',
 'IfcCommunicationsApplianceSCANNER',
 'IfcCompressor',
 'IfcCondenser',
 'IfcCondenserAIRCOOLED',
 'IfcController',
 'IfcControllerPROGRAMMABLE',
 'IfcControllerTWOPOSITION',
 'IfcCooledBeam',
 'IfcCooledBeamACTIVE',
 'IfcCooledBeamPASSIVE',
 'IfcCoolingTower',
 'IfcDamper',
 'IfcDamperBALANCINGDAMPER',
 'IfcDamperCONTROLDAMPER',
 'IfcDamperFIREDAMPER',
 'IfcDamperFIRESMOKEDAMPER',
 'IfcDamperFUMEHOODEXHAUST',
 'IfcDamperRELIEFDAMPER',
 'IfcDamperSMOKEDAMPER',
 'IfcDistributionBoard',
 'IfcDistributionBoardCONSUMERUNIT',
 'IfcDistributionBoardDISTRIBUTIONBOARD',
 'IfcDistributionBoardSWITCHBOARD',
 'IfcDistributionElement',
 'IfcDistributionSystem',
 'IfcDistributionSystemFIREPROTECTION',
 'IfcDistributionSystemSECURITY',
 'IfcDoorDOOR',
 'IfcDuctSegment',
 'IfcDuctSilencer',
 'IfcElectricAppliance',
 'IfcElectricApplianceDISHWASHER',
 'IfcElectricApplianceELECTRICCOOKER',
 'IfcElectricApplianceFREESTANDINGWATERHEATER',
 'IfcElectricApplianceFREEZER',
 'IfcElectricApplianceMICROWAVE',
 'IfcElectricApplianceREFRIGERATOR',
 'IfcElectricApplianceTUMBLEDRYER',
 'IfcElectricApplianceVENDINGMACHINE',
 'IfcElectricApplianceWASHINGMACHINE',
 'IfcElectricFlowStorageDevice',
 'IfcElectricFlowStorageDeviceBATTERY',
 'IfcElectricFlowStorageDeviceHARMONICFILTER',
 'IfcElectricFlowStorageDeviceUPS',
 'IfcElectricFlowTreatmentDevice',
 'IfcElectricGenerator',
 'IfcElectricGeneratorCHP',
 'IfcElectricGeneratorENGINEGENERATOR',
 'IfcElectricMotor',
 'IfcElectricTimeControlTIMECLOCK',
 'IfcEvaporativeCooler',
 'IfcEvaporator',
 'IfcFan',
 'IfcFastener',
 'IfcFilter',
 'IfcFilterAIRPARTICLEFILTER',
 'IfcFilterWATERFILTER',
 'IfcFireSuppressionTerminal',
 'IfcFireSuppressionTerminalHOSEREEL',
 'IfcFireSuppressionTerminalSPRINKLER',
 'IfcFlowMeter',
 'IfcFlowMeterENERGYMETER',
 'IfcFlowMeterGASMETER',
 'IfcFlowMeterWATERMETER',
 'IfcFlowTerminal',
 'IfcFlowTreatmentDevice',
 'IfcFurniture',
 'IfcFurnitureDESK',
 'IfcFurnitureSHELF',
 'IfcGroup',
 'IfcHeatExchanger',
 'IfcHeatExchangerPLATE',
 'IfcHumidifier',
 'IfcInterceptor',
 'IfcInterceptorGREASE',
 'IfcInterceptorOIL',
 'IfcLightFixture',
 'IfcLightFixtureDIRECTIONSOURCE',
 'IfcLightFixturePOINTSOURCE',
 'IfcLightFixtureSECURITYLIGHTING',
 'IfcMotorConnection',
 'IfcOutlet',
 'IfcOutletDATAOUTLET',
 'IfcOutletPOWEROUTLET',
 'IfcPipeSegment',
 'IfcProtectiveDevice',
 'IfcProtectiveDeviceCIRCUITBREAKER',
 'IfcProtectiveDeviceFUSEDISCONNECTOR',
 'IfcProtectiveDeviceRESIDUALCURRENTCIRCUITBREAKER',
 'IfcProtectiveDeviceVARISTOR',
 'IfcPump',
 'IfcPumpCIRCULATOR',
 'IfcPumpSUMPPUMP',
 'IfcSanitaryTerminalSANITARYFOUNTAIN',
 'IfcSanitaryTerminalSINK',
 'IfcSanitaryTerminalWASHHANDBASIN',
 'IfcSensor',
 'IfcSensorCO2SENSOR',
 'IfcSensorCONTACTSENSOR',
 'IfcSensorCOSENSOR',
 'IfcSensorFLOWSENSOR',
 'IfcSensorGASSENSOR',
 'IfcSensorHEATSENSOR',
 'IfcSensorHUMIDITYSENSOR',
 'IfcSensorLIGHTSENSOR',
 'IfcSensorMOVEMENTSENSOR',
 'IfcSensorPRESSURESENSOR',
 'IfcSensorRADIATIONSENSOR',
 'IfcSensorSMOKESENSOR',
 'IfcSensorSOUNDSENSOR',
 'IfcSensorTEMPERATURESENSOR',
 'IfcSensorWINDSENSOR',
 'IfcShadingDevice',
 'IfcSolarDeviceSOLARCOLLECTOR',
 'IfcSolarDeviceSOLARPANEL',
 'IfcSpaceHeater',
 'IfcSpaceHeaterRADIATOR',
 'IfcSpaceINTERNAL',
 'IfcStackTerminal',
 'IfcSwitchingDevice',
 'IfcSwitchingDeviceCONTACTOR',
 'IfcSwitchingDeviceDIMMERSWITCH',
 'IfcSwitchingDeviceKEYPAD',
 'IfcSwitchingDeviceSELECTORSWITCH',
 'IfcSwitchingDeviceSWITCHDISCONNECTOR',
 'IfcSwitchingDeviceTOGGLESWITCH',
 'IfcTank',
 'IfcTankBREAKPRESSURE',
 'IfcTankEXPANSION',
 'IfcTankSTORAGE',
 'IfcTankVESSEL',
 'IfcTransformer',
 'IfcTransformerINVERTER',
 'IfcTransformerRECTIFIER',
 'IfcTransportElementELEVATOR',
 'IfcTransportElementESCALATOR',
 'IfcTransportElementMOVINGWALKWAY',
 'IfcUnitaryControlElement',
 'IfcUnitaryControlElementALARMPANEL',
 'IfcUnitaryControlElementCONTROLPANEL',
 'IfcUnitaryControlElementGASDETECTIONPANEL',
 'IfcUnitaryControlElementINDICATORPANEL',
 'IfcUnitaryControlElementTHERMOSTAT',
 'IfcUnitaryControlElementWEATHERSTATION',
 'IfcUnitaryEquipment',
 'IfcUnitaryEquipmentAIRCONDITIONINGUNIT',
 'IfcUnitaryEquipmentAIRHANDLER',
 'IfcUnitaryEquipmentDEHUMIDIFIER',
 'IfcUnitaryEquipmentROOFTOPUNIT',
 'IfcUnitaryEquipmentSPLITSYSTEM',
 'IfcValve',
 'IfcValveAIRRELEASE',
 'IfcValveCHECK',
 'IfcValveCOMMISSIONING',
 'IfcValveDIVERTING',
 'IfcValveGASCOCK',
 'IfcValveISOLATING',
 'IfcValveMIXING',
 'IfcValvePRESSUREREDUCING',
 'IfcValvePRESSURERELIEF',
 'IfcValveSAFETYCUTOFF',
 'IfcValveSTEAMTRAP',
 'IfcWasteTerminal',
 'IfcWindow']

In [3]:
ifc2x3_unique = (
    df["ifc2x3"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

ifc2x3_unique_sorted = sorted(ifc2x3_unique)

ifc2x3_unique_sorted

['IfcActuator',
 'IfcActuatorELECTRICACTUATOR',
 'IfcAirTerminal',
 'IfcAirTerminalBox',
 'IfcAirTerminalBoxCONSTANTFLOW',
 'IfcAirToAirHeatRecovery',
 'IfcAirToAirHeatRecoveryROTARYWHEEL',
 'IfcAirToAirHeatRecoveryRUNAROUNDCOIL',
 'IfcAlarm',
 'IfcAlarmBELL',
 'IfcAlarmBREAKGLASSBUTTON',
 'IfcAlarmLIGHT',
 'IfcAlarmMANUALPULLBOX',
 'IfcAlarmSIREN',
 'IfcBoiler',
 'IfcBoilerSTEAM',
 'IfcBoilerWATER',
 'IfcBuildingElementProxy',
 'IfcCableCarrierSegment',
 'IfcCableCarrierSegmentCABLELADDERSEGMENT',
 'IfcCableCarrierSegmentCABLETRAYSEGMENT',
 'IfcCableCarrierSegmentCABLETRUNKINGSEGMENT',
 'IfcCableSegment',
 'IfcCableSegmentFIBERTUBE',
 'IfcChiller',
 'IfcChillerAIRCOOLED',
 'IfcChillerWATERCOOLED',
 'IfcCoil',
 'IfcCoilDXCOOLINGCOIL',
 'IfcCoilHYDRONICCOIL',
 'IfcCoilWATERCOOLINGCOIL',
 'IfcCoilWATERHEATINGCOIL',
 'IfcCompressor',
 'IfcCondenser',
 'IfcCondenserAIRCOOLED',
 'IfcController',
 'IfcControllerTWOPOSITION',
 'IfcCooledBeam',
 'IfcCoolingTower',
 'IfcDamper',
 'IfcDamperBALANCINGDAMPER',
 'IfcDamperCONTROLDAMPER',
 'IfcDamperFIREDAMPER',
 'IfcDamperFIRESMOKEDAMPER',
 'IfcDamperFUMEHOODEXHAUST',
 'IfcDamperRELIEFDAMPER',
 'IfcDamperSMOKEDAMPER',
 'IfcDiscreteAccessory',
 'IfcDoorStyle',
 'IfcDuctSegment',
 'IfcDuctSilencer',
 'IfcElectricAppliance',
 'IfcElectricApplianceDISHWASHER',
 'IfcElectricApplianceELECTRICCOOKER',
 'IfcElectricApplianceFREEZER',
 'IfcElectricApplianceMICROWAVE',
 'IfcElectricAppliancePRINTER',
 'IfcElectricApplianceREFRIGERATOR',
 'IfcElectricApplianceSCANNER',
 'IfcElectricApplianceTUMBLEDRYER',
 'IfcElectricApplianceVENDINGMACHINE',
 'IfcElectricApplianceWASHINGMACHINE',
 'IfcElectricApplianceWATERHEATER',
 'IfcElectricDistributionPoint',
 'IfcElectricDistributionPointALARMPANEL',
 'IfcElectricDistributionPointCONTROLPANEL',
 'IfcElectricDistributionPointDISTRIBUTIONBOARD',
 'IfcElectricDistributionPointGASDETECTORPANEL',
 'IfcElectricDistributionPointSWITCHBOARD',
 'IfcElectricFlowStorageDevice',
 'IfcElectricFlowStorageDeviceBATTERY',
 'IfcElectricFlowStorageDeviceHARMONICFILTER',
 'IfcElectricFlowStorageDeviceUPS',
 'IfcElectricGenerator',
 'IfcElectricMotor',
 'IfcElectricTimeControlTIMECLOCK',
 'IfcEvaporativeCooler',
 'IfcEvaporator',
 'IfcFan',
 'IfcFastener',
 'IfcFilter',
 'IfcFilterAIRPARTICLEFILTER',
 'IfcFilterWATERFILTER',
 'IfcFireSuppressionTerminal',
 'IfcFireSuppressionTerminalHOSEREEL',
 'IfcFireSuppressionTerminalSPRINKLER',
 'IfcFlowMeter',
 'IfcFlowMeterENERGYMETER',
 'IfcFlowMeterGASMETER',
 'IfcFlowMeterWATERMETER',
 'IfcFurniture',
 'IfcGasTerminalGASAPPLIANCE',
 'IfcHeatExchanger',
 'IfcHeatExchangerPLATE',
 'IfcHumidifier',
 'IfcLightFixture',
 'IfcLightFixtureDIRECTIONSOURCE',
 'IfcLightFixturePOINTSOURCE',
 'IfcMotorConnection',
 'IfcOutlet',
 'IfcOutletCOMMUNICATIONSOUTLET',
 'IfcOutletPOWEROUTLET',
 'IfcPipeSegment',
 'IfcProtectiveDevice',
 'IfcProtectiveDeviceCIRCUITBREAKER',
 'IfcProtectiveDeviceFUSEDISCONNECTOR',
 'IfcProtectiveDeviceRESIDUALCURRENTCIRCUITBREAKER',
 'IfcProtectiveDeviceVARISTOR',
 'IfcPump',
 'IfcPumpCIRCULATOR',
 'IfcSanitaryTerminalSANITARYFOUNTAIN',
 'IfcSanitaryTerminalSINK',
 'IfcSanitaryTerminalWASHHANDBASIN',
 'IfcSensor',
 'IfcSensorCO2SENSOR',
 'IfcSensorFLOWSENSOR',
 'IfcSensorGASSENSOR',
 'IfcSensorHEATSENSOR',
 'IfcSensorHUMIDITYSENSOR',
 'IfcSensorLIGHTSENSOR',
 'IfcSensorMOVEMENTSENSOR',
 'IfcSensorPRESSURESENSOR',
 'IfcSensorSMOKESENSOR',
 'IfcSensorSOUNDSENSOR',
 'IfcSensorTEMPERATURESENSOR',
 'IfcSpace',
 'IfcSpaceHeater',
 'IfcStackTerminal',
 'IfcSwitchingDevice',
 'IfcSwitchingDeviceCONTACTOR',
 'IfcSwitchingDeviceSWITCHDISCONNECTOR',
 'IfcSwitchingDeviceTOGGLESWITCH',
 'IfcTank',
 'IfcTankEXPANSION',
 'IfcTransformer',
 'IfcTransformerINVERTER',
 'IfcTransportElementELEVATOR',
 'IfcTransportElementESCALATOR',
 'IfcTransportElementMOVINGWALKWAY',
 'IfcUnitaryEquipment',
 'IfcUnitaryEquipmentAIRCONDITIONINGUNIT',
 'IfcUnitaryEquipmentAIRHANDLER',
 'IfcUnitaryEquipmentROOFTOPUNIT',
 'IfcUnitaryEquipmentSPLITSYSTEM',
 'IfcValve',
 'IfcValveAIRRELEASE',
 'IfcValveCHECK',
 'IfcValveCOMMISSIONING',
 'IfcValveDIVERTING',
 'IfcValveGASCOCK',
 'IfcValveISOLATING',
 'IfcValveMIXING',
 'IfcValvePRESSUREREDUCING',
 'IfcValvePRESSURERELIEF',
 'IfcValveSAFETYCUTOFF',
 'IfcValveSTEAMTRAP',
 'IfcWasteTerminal',
 'IfcWasteTerminalGREASEINTERCEPTOR',
 'IfcWasteTerminalOILINTERCEPTOR',
 'IfcWindowStyle']

Entity と PredefinedType を分解する関数定義

In [4]:
def split_ifc_entity_and_type(value):
    if pd.isna(value):
        return pd.Series([None, None])

    value = str(value)

    match = re.match(r"^(Ifc[A-Za-z0-9]+?)([A-Z]+)$", value)

    if match:
        entity = match.group(1)
        predefined_type = match.group(2)
        return pd.Series([entity, predefined_type])
    else:
        return pd.Series([value, None])

In [5]:
df[["ifc2x3_entity", "ifc2x3_predefined_type"]] = (
    df["ifc2x3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc2x3", "ifc2x3_entity", "ifc2x3_predefined_type"]].head()

                        ifc2x3         ifc2x3_entity ifc2x3_predefined_type
0                IfcController         IfcController                   None
1  IfcElectricApplianceSCANNER  IfcElectricAppliance                SCANNER
2                          NaN                  None                   None
3           IfcSwitchingDevice    IfcSwitchingDevice                   None
4  IfcElectricApplianceSCANNER  IfcElectricAppliance                SCANNER

In [6]:
df[["ifc4_3_entity", "ifc4_3_predefined_type"]] = (
    df["ifc4_3"]
    .apply(split_ifc_entity_and_type)
)

df[["ifc4_3", "ifc4_3_entity", "ifc4_3_predefined_type"]].head()

,ifc4_3,ifc4_3_entity,ifc4_3_predefined_type
0,IfcController,IfcController,None
1,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER
2,IfcDistributionSystemSECURITY,IfcDistributionSystem,SECURITY
3,IfcSwitchingDevice,IfcSwitchingDevice,None
4,IfcCommunicationsApplianceSCANNER,IfcCommunicationsAppliance,SCANNER

IFC要素抽出プログラム

In [7]:
import ifcopenshell

def extract_ifc_elements(ifc_path):
    model = ifcopenshell.open(ifc_path)

    elements = []

    for obj in model.by_type("IfcObject"):
        entity_name = obj.is_a()

        predefined_type = None
        if hasattr(obj, "PredefinedType"):
            predefined_type = obj.PredefinedType

        elements.append({
            "global_id": obj.GlobalId,
            "ifc_entity": entity_name,
            "predefined_type": None if predefined_type in [None, ""] else str(predefined_type)
        })

    return elements

In [8]:
ifc_elements = extract_ifc_elements(r"C:\Users\Owner\Documents\25952501_RioSaijo\IFC_ToBrick_IoT_Interoperability_Project\data\In\ifc\raw\51M-SKA-00-00-M3-MEP-0001_IFC 2x3-P01.ifc")

判定関数

In [13]:
bdns_sub_df = df[["ifc2x3_entity", "ifc2x3_predefined_type"]]

In [16]:
bdns_exact_set = set(
    (
        row["ifc2x3_entity"],
        str(row["ifc2x3_predefined_type"]).upper()
    )
    for _, row in bdns_sub_df.iterrows()
    if not pd.isna(row["ifc2x3_predefined_type"])
)

In [17]:
bdns_exact_set

{('IfcActuator', 'ELECTRICACTUATOR'),
 ('IfcAirTerminalBox', 'CONSTANTFLOW'),
 ('IfcAirToAirHeatRecovery', 'ROTARYWHEEL'),
 ('IfcAirToAirHeatRecovery', 'RUNAROUNDCOIL'),
 ('IfcAlarm', 'BELL'),
 ('IfcAlarm', 'BREAKGLASSBUTTON'),
 ('IfcAlarm', 'LIGHT'),
 ('IfcAlarm', 'MANUALPULLBOX'),
 ('IfcAlarm', 'SIREN'),
 ('IfcBoiler', 'STEAM'),
 ('IfcBoiler', 'WATER'),
 ('IfcCableCarrierSegment', 'CABLELADDERSEGMENT'),
 ('IfcCableCarrierSegment', 'CABLETRAYSEGMENT'),
 ('IfcCableCarrierSegment', 'CABLETRUNKINGSEGMENT'),
 ('IfcCableSegment', 'FIBERTUBE'),
 ('IfcChiller', 'AIRCOOLED'),
 ('IfcChiller', 'WATERCOOLED'),
 ('IfcCoil', 'DXCOOLINGCOIL'),
 ('IfcCoil', 'HYDRONICCOIL'),
 ('IfcCoil', 'WATERCOOLINGCOIL'),
 ('IfcCoil', 'WATERHEATINGCOIL'),
 ('IfcCondenser', 'AIRCOOLED'),
 ('IfcController', 'TWOPOSITION'),
 ('IfcDamper', 'BALANCINGDAMPER'),
 ('IfcDamper', 'CONTROLDAMPER'),
 ('IfcDamper', 'FIREDAMPER'),
 ('IfcDamper', 'FIRESMOKEDAMPER'),
 ('IfcDamper', 'FUMEHOODEXHAUST'),
 ('IfcDamper', 'RELIEFDAMPER'),
 ('IfcDamper', 'SMOKEDAMPER'),
 ('IfcElectricAppliance', 'DISHWASHER'),
 ('IfcElectricAppliance', 'ELECTRICCOOKER'),
 ('IfcElectricAppliance', 'FREEZER'),
 ('IfcElectricAppliance', 'MICROWAVE'),
 ('IfcElectricAppliance', 'PRINTER'),
 ('IfcElectricAppliance', 'REFRIGERATOR'),
 ('IfcElectricAppliance', 'SCANNER'),
 ('IfcElectricAppliance', 'TUMBLEDRYER'),
 ('IfcElectricAppliance', 'VENDINGMACHINE'),
 ('IfcElectricAppliance', 'WASHINGMACHINE'),
 ('IfcElectricAppliance', 'WATERHEATER'),
 ('IfcElectricDistributionPoint', 'ALARMPANEL'),
 ('IfcElectricDistributionPoint', 'CONTROLPANEL'),
 ('IfcElectricDistributionPoint', 'DISTRIBUTIONBOARD'),
 ('IfcElectricDistributionPoint', 'GASDETECTORPANEL'),
 ('IfcElectricDistributionPoint', 'SWITCHBOARD'),
 ('IfcElectricFlowStorageDevice', 'BATTERY'),
 ('IfcElectricFlowStorageDevice', 'HARMONICFILTER'),
 ('IfcElectricFlowStorageDevice', 'UPS'),
 ('IfcElectricTimeControl', 'TIMECLOCK'),
 ('IfcFilter', 'AIRPARTICLEFILTER'),
 ('IfcFilter', 'WATERFILTER'),
 ('IfcFireSuppressionTerminal', 'HOSEREEL'),
 ('IfcFireSuppressionTerminal', 'SPRINKLER'),
 ('IfcFlowMeter', 'ENERGYMETER'),
 ('IfcFlowMeter', 'GASMETER'),
 ('IfcFlowMeter', 'WATERMETER'),
 ('IfcGasTerminal', 'GASAPPLIANCE'),
 ('IfcHeatExchanger', 'PLATE'),
 ('IfcLightFixture', 'DIRECTIONSOURCE'),
 ('IfcLightFixture', 'POINTSOURCE'),
 ('IfcOutlet', 'COMMUNICATIONSOUTLET'),
 ('IfcOutlet', 'POWEROUTLET'),
 ('IfcProtectiveDevice', 'CIRCUITBREAKER'),
 ('IfcProtectiveDevice', 'FUSEDISCONNECTOR'),
 ('IfcProtectiveDevice', 'RESIDUALCURRENTCIRCUITBREAKER'),
 ('IfcProtectiveDevice', 'VARISTOR'),
 ('IfcPump', 'CIRCULATOR'),
 ('IfcSanitaryTerminal', 'SANITARYFOUNTAIN'),
 ('IfcSanitaryTerminal', 'SINK'),
 ('IfcSanitaryTerminal', 'WASHHANDBASIN'),
 ('IfcSensor', 'FLOWSENSOR'),
 ('IfcSensor', 'GASSENSOR'),
 ('IfcSensor', 'HEATSENSOR'),
 ('IfcSensor', 'HUMIDITYSENSOR'),
 ('IfcSensor', 'LIGHTSENSOR'),
 ('IfcSensor', 'MOVEMENTSENSOR'),
 ('IfcSensor', 'PRESSURESENSOR'),
 ('IfcSensor', 'SMOKESENSOR'),
 ('IfcSensor', 'SOUNDSENSOR'),
 ('IfcSensor', 'TEMPERATURESENSOR'),
 ('IfcSensorCO2', 'SENSOR'),
 ('IfcSwitchingDevice', 'CONTACTOR'),
 ('IfcSwitchingDevice', 'SWITCHDISCONNECTOR'),
 ('IfcSwitchingDevice', 'TOGGLESWITCH'),
 ('IfcTank', 'EXPANSION'),
 ('IfcTransformer', 'INVERTER'),
 ('IfcTransportElement', 'ELEVATOR'),
 ('IfcTransportElement', 'ESCALATOR'),
 ('IfcTransportElement', 'MOVINGWALKWAY'),
 ('IfcUnitaryEquipment', 'AIRCONDITIONINGUNIT'),
 ('IfcUnitaryEquipment', 'AIRHANDLER'),
 ('IfcUnitaryEquipment', 'ROOFTOPUNIT'),
 ('IfcUnitaryEquipment', 'SPLITSYSTEM'),
 ('IfcValve', 'AIRRELEASE'),
 ('IfcValve', 'CHECK'),
 ('IfcValve', 'COMMISSIONING'),
 ('IfcValve', 'DIVERTING'),
 ('IfcValve', 'GASCOCK'),
 ('IfcValve', 'ISOLATING'),
 ('IfcValve', 'MIXING'),
 ('IfcValve', 'PRESSUREREDUCING'),
 ('IfcValve', 'PRESSURERELIEF'),
 ('IfcValve', 'SAFETYCUTOFF'),
 ('IfcValve', 'STEAMTRAP'),
 ('IfcWasteTerminal', 'GREASEINTERCEPTOR'),
 ('IfcWasteTerminal', 'OILINTERCEPTOR')}

In [18]:
bdns_entity_only_set = set(
    row["ifc2x3_entity"]
    for _, row in bdns_sub_df.iterrows()
    if pd.isna(row["ifc2x3_predefined_type"])
)

In [20]:
def is_defined_in_bdns(ifc_element,
                       bdns_exact_set,
                       bdns_entity_only_set):

    entity = ifc_element["ifc_entity"]
    ptype = ifc_element["predefined_type"]

    if entity in bdns_entity_only_set:
        return True

    if ptype is None:
        return False

    return (entity, ptype.upper()) in bdns_exact_set

In [21]:
for elem in ifc_elements:
    elem["allow_bdns_tag"] = is_defined_in_bdns(
        elem,
        bdns_exact_set,
        bdns_entity_only_set
    )

In [22]:
ifc_elements

[{'global_id': '3T5NVXezz9DRBS$A4Fkvli',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkk',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvku',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkf',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvks',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkr',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '0jKcM_OSPB4BmhGqdswtba',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkh',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlj',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkg',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvki',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkl',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkn',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkm',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlo',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkp',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvl3',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkq',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkv',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkM',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGf',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvlZ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkx',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkw',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkR',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvkz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkP',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvky',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk_',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3DSlrZl8bECgisAtKFLnbI',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk4',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuOY',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk1',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk0',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvld',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '0jKcM_OSPB4BmhGqdswsOK',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk2',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk5',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlt',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvl2',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvln',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlk',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvlY',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkS',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkT',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkO',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '0jKcM_OSPB4BmhGqdswtZr',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk6',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvk8',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkL',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkK',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvlW',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvlX',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkvkV',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGc',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlf',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlc',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvll',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkupz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlm',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvls',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlv',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlx',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvlw',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvke',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvly',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkvl1',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGS',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHq',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHf',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH3',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHo',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHk',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkupy',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3FaTDFib5BNuNO2PyVA$qX',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGn',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGk',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGM',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGw',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGj',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGt',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGW',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGr',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGm',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '37vN_1tcf5D958JDzyrSdW',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHg',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGd',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGh',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGg',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHt',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGi',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGl',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHp',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH0',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGp',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGq',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGK',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHZ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGs',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGv',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGO',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGu',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGN',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGx',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '37vN_1tcf5D958JDzyrSc6',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG3',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGy',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG$',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHa',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuQy',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG1',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG0',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHl',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGQ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGT',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGR',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGP',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '1ywcqmyvbE4vGgHY9_86_H',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG5',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuG7',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGG',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGJ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGV',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHW',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '1DeeSLvVz7Gh7FoqWMazc_',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHc',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHd',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '37vN_1tcf5D958JDzyrSck',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHi',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '37vN_1tcf5D958JDzyrSXF',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHn',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHs',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHu',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHw',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHx',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuGZ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH$',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH_',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuIz',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHT',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuII',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '2TJOFZ4n14hxEQb77RrD$_',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuJX',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuIG',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4Fkup$',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuIB',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHE',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuIt',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHQ',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHD',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHN',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH2',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHL',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuHG',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '2TJOFZ4n14hxEQb77RrDMN',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuI8',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},
 {'global_id': '3T5NVXezz9DRBS$A4FkuH7',
  'ifc_entity': 'IfcSystem',
  'predefined_type': None,
  'allow_bdns_tag': False},

In [26]:
bdns_true_elements = [
    elem for elem in ifc_elements
    if elem.get("allow_bdns_tag", False)
]

In [27]:
bdns_true_elements

[{'global_id': '3edPp6VUPFUPmy7DmdPW$P',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3edPp6VUPFUPmy7DmdP$bi',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3edPp6VUPFUPmy7DmdPzeS',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3edPp6VUPFUPmy7DmdPztO',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '1zT1vkSdP5geic0HutmWkl',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3ThYxDUCD5tewfq2Thu9$0',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3ThYxDUCD5tewfq2Thu9Xh',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3ThYxDUCD5tewfq2Thu9ZK',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3ThYxDUCD5tewfq2Thu9b2',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3ThYxDUCD5tewfq2Thu9ci',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEA',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrED',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEC',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEF',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEE',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEH',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEG',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEJ',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEI',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEL',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEK',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEN',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrEP',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrFf',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrFe',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkrFj',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkrs3',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkrtm',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkrvq',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkr_c',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOC',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOF',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOE',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOH',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOG',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOJ',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOI',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOL',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOK',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqON',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOP',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOO',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqOR',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqPh',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqPg',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqPl',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkq0z',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkq1g',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkq3k',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkq8W',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwA',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwD',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwC',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwF',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwE',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwH',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwG',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwJ',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwI',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwL',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwK',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwN',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqwP',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkqxf',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkqxe',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkqxj',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqYv',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqZc',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkqbh',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkqfT',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxJw',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxND',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxNE',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxNJ',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxNK',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxNM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxNR',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxPi',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxQz',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxRn',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxSr',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx5j',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx6w',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx7i',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx74',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx7H',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx9d',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx9R',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxAW',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxAI',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxr1',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvG',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvL',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvR',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvT',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxvU',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxxp',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxy0',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxzq',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkx_u',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxdn',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxe_',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxfm',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxf8',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxfL',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxhh',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxhV',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkxia',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkxiM',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwMS',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOd',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOe',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOj',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOk',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOm',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwOr',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwPi',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwQv',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwQU',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwRs',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw0C',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw1a',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw14',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw1S',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw2f',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw3m',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw3I',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkwv6',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkwwj',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwwA',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkwxt',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwxO',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw$H',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkw$J',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwWD',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwWE',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwZT',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwZU',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwaW',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4FkwaY',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,
  'allow_bdns_tag': True},
 {'global_id': '3T5NVXezz9DRBS$A4Fkwaa',
  'ifc_entity': 'IfcBuildingElementProxy',
  'predefined_type': None,

In [28]:
bdns_true_count = len(bdns_true_elements)

In [29]:
bdns_true_count

223